name: xcodeproj
description: A library for reading and modifying XCode projects.
version: 0.2.3
homepage: https://github.com/appsup-dart/xcodeproj
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  petitparser: ^5.0.0
  xml: ^6.0.0
  snapshot:
    git:
      url: git@github.com:bvoq/snapshot.git
      ref: "831db0de24842b104440554f9e3d4919fcb1db55"
  crypto: ^3.0.0
  path: ^1.8.0
  quiver: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
